version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
      port: 3000:3000
    environment:
      - PEXELS_API_KEY=${PEXELS_API_KEY}
      - FREESOUND_API_KEY=${FREESOUND_API_KEY}
      - APP_NAME=${APP_NAME}
      - APP_VERSION=${APP_VERSION}
      - APP_PORT={APP_PORT}
      - APP_URL=${APP_URL}
