version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
      port: 3000:3000
    environment:
      - PEXELS_API_KEY=${PEXELS_API_KEY}
      - FREESOUND_API_KEY=${FREESOUND_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - TIKTOK_SESSION_ID=${TIKTOK_SESSION_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_VIDEO_KEY=${API_VIDEO_KEY}